base_configs:
  # file configs:
  train_file: /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w-r80/train.bin
  dev_file: /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w/dev.bin
  test_file: /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w-r80/test.bin
  vocab: /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w-r80/vocab.bin
  eval_lists:
    - /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w-r80/mt03.ref0
  logdir: /mnt/cephfs_wj/bytetrans/baoyu.nlp/experiments/logs
  model_dir: /mnt/cephfs_wj/bytetrans/baoyu.nlp/experiments/models
  exp_name: ~
  task_type: Translation
  # train configs
  start_iter: 0
  batch_size: 50
  log_every: 50
  dev_every: 1000
  lr: 0.0005
  lr_decay: 0.5
  patience: 20
  clip_grad: 5.0
  reset_optimizer: false