base_configs:
  # file configs:
  train_file: /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w-r80/train.bin
  dev_file: /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w/dev.bin
  test_file: /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w-r80/test.bin
  vocab: /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w-r80/vocab.bin
  eval_lists:
    - /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w/mt03.ref0
    - /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w/mt03.ref1
    - /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w/mt03.ref2
    - /mnt/cephfs_wj/bytetrans/baoyu.nlp/data/zh-en-134w/mt03.ref3
  logdir: /data00/home/baoyu.nlp/run_logs
  model_dir: /data00/home/baoyu.nlp/run_models
  exp_name: ~
  task_type: Translation
  # train configs
  start_iter: 0
  batch_size: 30
  log_every: 50
  dev_every: 500
  lr: 0.001
  lr_decay: 0.8
  patience: 10
  clip_grad: 5.0
  reset_optimizer: false